// SPDX-License-Identifier: MIT
// Copyright (c) 2026 InstaChord Corp.

#ifndef KANTAN_SAMPLER_SAMPLES_HPP
#define KANTAN_SAMPLER_SAMPLES_HPP

// 開発検証用の組み込みサンプル音源 (docs/Sample_Sound/ の WAV をバイナリ埋め込み)
// 将来的には TFカードからの読み込み・ユーザー録音に置き換える。
// アセンブラシンボルを定義するため、このヘッダは1つの翻訳単位からのみ include すること。
// (埋め込み手法は main/file_manage.cpp の IMPORT_FILE と同一)

#include <stdint.h>
#include <stddef.h>
#include <array>

namespace sampler_ns {
//-------------------------------------------------------------------------

#if defined (__APPLE__) && defined (__MACH__) && defined (__arm64__)

#define SAMPLER_IMPORT_WAV(filename, symbol) \
extern "C" const uint8_t symbol[], sizeof_##symbol[]; \
asm (\
  ".section __DATA,__data \n"\
  ".balign 4\n_"\
  #symbol ":\n"\
  ".incbin \"docs/Sample_Sound/" filename "\"\n"\
  ".global _sizeof_" #symbol "\n"\
  ".set _sizeof_" #symbol ", . - _" #symbol "\n"\
  ".global _" #symbol "\n"\
  ".balign 4\n"\
  ".text \n")

#else

#define SAMPLER_IMPORT_WAV(filename, symbol) \
extern "C" const uint8_t symbol[], sizeof_##symbol[]; \
asm (\
  ".section .rodata\n"\
  ".balign 4\n"\
  ".global " #symbol "\n"\
  #symbol ":\n"\
  ".incbin \"docs/Sample_Sound/" filename "\"\n"\
  ".global sizeof_" #symbol "\n"\
  ".set sizeof_" #symbol ", . - " #symbol "\n"\
  ".balign 4\n"\
  ".section \".text\"\n")

#endif

SAMPLER_IMPORT_WAV("kick.wav",                                wav_kick);
SAMPLER_IMPORT_WAV("Snare.wav",                               wav_snare);
SAMPLER_IMPORT_WAV("clap.wav",                                wav_clap);
SAMPLER_IMPORT_WAV("Hat.wav",                                 wav_hihat);
SAMPLER_IMPORT_WAV("chin.wav",                                wav_chin);
SAMPLER_IMPORT_WAV("Cowbell.wav",                             wav_cowbell);
SAMPLER_IMPORT_WAV("Piko.wav",                                wav_piko);
SAMPLER_IMPORT_WAV("Tom.wav",                                 wav_tom);
SAMPLER_IMPORT_WAV("Air-Horn.wav",                            wav_air_horn);
SAMPLER_IMPORT_WAV("Cat.wav",                                 wav_cat);
SAMPLER_IMPORT_WAV("Gunshot.wav",                             wav_gunshot);
SAMPLER_IMPORT_WAV("Hat_Close.wav",                           wav_hat_close);
SAMPLER_IMPORT_WAV("Jump.wav",                                wav_jump);
SAMPLER_IMPORT_WAV("Laser.wav",                               wav_laser);
SAMPLER_IMPORT_WAV("Sheep.wav",                               wav_sheep);
SAMPLER_IMPORT_WAV("Acoustic_Drums/01_Acoustic_Tom_Low.wav",  wav_acoustic_tom_low);
SAMPLER_IMPORT_WAV("Acoustic_Drums/02_Acoustic_Tom_Mid.wav",  wav_acoustic_tom_mid);
SAMPLER_IMPORT_WAV("Acoustic_Drums/03_Acoustic_Tom_High.wav", wav_acoustic_tom_high);
SAMPLER_IMPORT_WAV("Acoustic_Drums/04_Acoustic_Rim.wav",      wav_acoustic_rim);
SAMPLER_IMPORT_WAV("Acoustic_Drums/05_Acoustic_Crash.wav",    wav_acoustic_crash);
SAMPLER_IMPORT_WAV("Acoustic_Drums/06_Acoustic_Ride.wav",     wav_acoustic_ride);
SAMPLER_IMPORT_WAV("Acoustic_Drums/07_Acoustic_Shaker.wav",   wav_acoustic_shaker);
SAMPLER_IMPORT_WAV("Chiptune_Drums/01_Chip_Kick.wav",         wav_chip_kick);
SAMPLER_IMPORT_WAV("Chiptune_Drums/02_Chip_Snare.wav",        wav_chip_snare);
SAMPLER_IMPORT_WAV("Chiptune_Drums/03_Chip_Clap.wav",         wav_chip_clap);
SAMPLER_IMPORT_WAV("Chiptune_Drums/04_Chip_Hat_Closed.wav",   wav_chip_hat_closed);
SAMPLER_IMPORT_WAV("Chiptune_Drums/05_Chip_Hat_Open.wav",     wav_chip_hat_open);
SAMPLER_IMPORT_WAV("Chiptune_Drums/06_Chip_Tom.wav",          wav_chip_tom);
SAMPLER_IMPORT_WAV("Chiptune_Drums/07_Chip_Rim.wav",          wav_chip_rim);
SAMPLER_IMPORT_WAV("Chiptune_Drums/08_Chip_Cowbell.wav",      wav_chip_cowbell);
SAMPLER_IMPORT_WAV("Dance_Drums/01_Dance_Kick.wav",           wav_dance_kick);
SAMPLER_IMPORT_WAV("Dance_Drums/02_Dance_Snare.wav",          wav_dance_snare);
SAMPLER_IMPORT_WAV("Dance_Drums/03_Dance_Rim.wav",            wav_dance_rim);
SAMPLER_IMPORT_WAV("Dance_Drums/04_Dance_Clap.wav",           wav_dance_clap);
SAMPLER_IMPORT_WAV("Dance_Drums/05_Dance_Tom_Low.wav",        wav_dance_tom_low);
SAMPLER_IMPORT_WAV("Dance_Drums/06_Dance_Tom_Mid.wav",        wav_dance_tom_mid);
SAMPLER_IMPORT_WAV("Dance_Drums/07_Dance_Tom_High.wav",       wav_dance_tom_high);
SAMPLER_IMPORT_WAV("Dance_Drums/08_Dance_Hat_Closed.wav",     wav_dance_hat_closed);
SAMPLER_IMPORT_WAV("Dance_Drums/09_Dance_Shaker.wav",         wav_dance_shaker);
SAMPLER_IMPORT_WAV("Dance_Drums/10_Dance_Crash.wav",          wav_dance_crash);
SAMPLER_IMPORT_WAV("Dance_Drums/11_Dance_Ride.wav",           wav_dance_ride);
SAMPLER_IMPORT_WAV("Dance_Drums/12_Dance_Hat_Open.wav",       wav_dance_hat_open);
// Deterministic mono factory sources generated by generate_presets.py.
// One-shots are 18 kHz; short loopable synth sources are 48 kHz/C4.
SAMPLER_IMPORT_WAV("Generated_Presets/Kick_Deep.wav",         wav_preset_kick_deep);
SAMPLER_IMPORT_WAV("Generated_Presets/Kick_Tight.wav",        wav_preset_kick_tight);
SAMPLER_IMPORT_WAV("Generated_Presets/Snare_Soft.wav",        wav_preset_snare_soft);
SAMPLER_IMPORT_WAV("Generated_Presets/Snare_Bright.wav",      wav_preset_snare_bright);
SAMPLER_IMPORT_WAV("Generated_Presets/Tom_Low.wav",           wav_preset_tom_low);
SAMPLER_IMPORT_WAV("Generated_Presets/Tom_High.wav",          wav_preset_tom_high);
SAMPLER_IMPORT_WAV("Generated_Presets/HiHat_Closed.wav",      wav_preset_hihat_closed);
SAMPLER_IMPORT_WAV("Generated_Presets/HiHat_Open.wav",        wav_preset_hihat_open);
SAMPLER_IMPORT_WAV("Generated_Presets/Cymbal_Crash.wav",      wav_preset_cymbal_crash);
SAMPLER_IMPORT_WAV("Generated_Presets/Cymbal_Ride.wav",       wav_preset_cymbal_ride);
SAMPLER_IMPORT_WAV("Generated_Presets/Perc_Shaker.wav",       wav_preset_perc_shaker);
SAMPLER_IMPORT_WAV("Generated_Presets/Perc_Wood.wav",         wav_preset_perc_wood);
SAMPLER_IMPORT_WAV("Generated_Presets/Bass_Sub.wav",          wav_preset_bass_sub);
SAMPLER_IMPORT_WAV("Generated_Presets/Bass_Saw.wav",          wav_preset_bass_saw);
SAMPLER_IMPORT_WAV("Generated_Presets/Lead_Square.wav",       wav_preset_lead_square);
SAMPLER_IMPORT_WAV("Generated_Presets/Lead_Sync.wav",         wav_preset_lead_sync);
SAMPLER_IMPORT_WAV("Generated_Presets/Pad_Warm.wav",          wav_preset_pad_warm);
SAMPLER_IMPORT_WAV("Generated_Presets/Pad_Airy.wav",          wav_preset_pad_airy);
SAMPLER_IMPORT_WAV("Generated_Presets/Keys_EP.wav",           wav_preset_keys_ep);
SAMPLER_IMPORT_WAV("Generated_Presets/Keys_Organ.wav",        wav_preset_keys_organ);
SAMPLER_IMPORT_WAV("Generated_Presets/Pluck_Nylon.wav",       wav_preset_pluck_nylon);
SAMPLER_IMPORT_WAV("Generated_Presets/Pluck_Harp.wav",        wav_preset_pluck_harp);
SAMPLER_IMPORT_WAV("Generated_Presets/Mallet_Bell.wav",       wav_preset_mallet_bell);
SAMPLER_IMPORT_WAV("Generated_Presets/Mallet_Marimba.wav",    wav_preset_mallet_marimba);
SAMPLER_IMPORT_WAV("Generated_Presets/Voice_Ah.wav",          wav_preset_voice_ah);
SAMPLER_IMPORT_WAV("Generated_Presets/Voice_Ooh.wav",         wav_preset_voice_ooh);
SAMPLER_IMPORT_WAV("Generated_Presets/FX_Riser.wav",          wav_preset_fx_riser);
SAMPLER_IMPORT_WAV("Generated_Presets/FX_Fall.wav",           wav_preset_fx_fall);
SAMPLER_IMPORT_WAV("Generated_Presets/Wave_Sine.wav",         wav_preset_wave_sine);
SAMPLER_IMPORT_WAV("Generated_Presets/Wave_Saw.wav",          wav_preset_wave_saw);

#undef SAMPLER_IMPORT_WAV

enum class sample_category_t : uint8_t {
  kick,
  snare,
  tom,
  hihat,
  cymbal,
  percussion,
  bass,
  lead,
  pad,
  keys,
  pluck,
  mallet,
  voice,
  fx,
  waveform,
  count,
};

static constexpr const char* sample_category_names[] = {
  "Kick", "Snare", "Tom", "HiHat", "Cymbal", "Percussion",
  "Bass", "Lead", "Pad", "Keys", "Pluck", "Mallet", "Voice", "FX", "Waveform",
};
static constexpr size_t sample_category_count = (size_t)sample_category_t::count;
static_assert(sizeof(sample_category_names) / sizeof(sample_category_names[0]) == sample_category_count,
              "sample category name table mismatch");

static constexpr const char* sample_category_name(sample_category_t category)
{
  const size_t index = (size_t)category;
  return index < sample_category_count ? sample_category_names[index] : "Other";
}

struct sample_source_t {
  const char* name;        // Pad表示用の短い名前
  const uint8_t* data;     // WAVファイル先頭
  const uint8_t* size_sym; // サイズシンボル (アドレス値がサイズ)
  sample_category_t category = sample_category_t::fx;
  uint8_t base_note = 0xFF;  // 0xFF=自動解析。短尺シンセ素材はC4(60)を明示。
  uint16_t synth_loop_start_ms = 0;
  uint16_t synth_loop_end_ms = 0;
  uint16_t synth_loop_crossfade_ms = 0;
  uint16_t synth_release_ms = 120;
  size_t size(void) const { return (size_t)size_sym; }
  bool hasSynthPreset(void) const {
    return base_note <= 127 && synth_loop_end_ms > synth_loop_start_ms;
  }
};

static const sample_source_t builtin_samples[] = {
  { "KICK",    wav_kick,          sizeof_wav_kick,          sample_category_t::kick       },
  { "SNARE",   wav_snare,         sizeof_wav_snare,         sample_category_t::snare      },
  { "CLAP",    wav_clap,          sizeof_wav_clap,          sample_category_t::percussion },
  { "HAT",     wav_hihat,         sizeof_wav_hihat,         sample_category_t::hihat      },
  { "PIKO",    wav_piko,          sizeof_wav_piko,          sample_category_t::fx         },
  { "COWBELL", wav_cowbell,       sizeof_wav_cowbell,       sample_category_t::percussion },
  { "CHIN",    wav_chin,          sizeof_wav_chin,          sample_category_t::cymbal     },
  { "TOM",     wav_tom,           sizeof_wav_tom,           sample_category_t::tom        },
  { "AIR HORN", wav_air_horn,      sizeof_wav_air_horn,      sample_category_t::fx         },
  { "CAT",      wav_cat,           sizeof_wav_cat,           sample_category_t::voice      },
  { "GUNSHOT",  wav_gunshot,       sizeof_wav_gunshot,       sample_category_t::fx         },
  { "HAT CLOSE",wav_hat_close,     sizeof_wav_hat_close,     sample_category_t::hihat      },
  { "JUMP",     wav_jump,          sizeof_wav_jump,          sample_category_t::fx         },
  { "LASER",    wav_laser,         sizeof_wav_laser,         sample_category_t::fx         },
  { "SHEEP",    wav_sheep,         sizeof_wav_sheep,         sample_category_t::voice      },
  { "TOM LOW",  wav_acoustic_tom_low,  sizeof_wav_acoustic_tom_low,  sample_category_t::tom        },
  { "TOM MID",  wav_acoustic_tom_mid,  sizeof_wav_acoustic_tom_mid,  sample_category_t::tom        },
  { "TOM HIGH", wav_acoustic_tom_high, sizeof_wav_acoustic_tom_high, sample_category_t::tom        },
  { "RIM",      wav_acoustic_rim,      sizeof_wav_acoustic_rim,      sample_category_t::percussion },
  { "CRASH",    wav_acoustic_crash,    sizeof_wav_acoustic_crash,    sample_category_t::cymbal     },
  { "RIDE",     wav_acoustic_ride,     sizeof_wav_acoustic_ride,     sample_category_t::cymbal     },
  { "SHAKER",   wav_acoustic_shaker,   sizeof_wav_acoustic_shaker,   sample_category_t::percussion },
  { "CHIP KICK",   wav_chip_kick,       sizeof_wav_chip_kick,       sample_category_t::kick       },
  { "CHIP SNARE",  wav_chip_snare,      sizeof_wav_chip_snare,      sample_category_t::snare      },
  { "CHIP CLAP",   wav_chip_clap,       sizeof_wav_chip_clap,       sample_category_t::percussion },
  { "CHIP HAT C",  wav_chip_hat_closed, sizeof_wav_chip_hat_closed, sample_category_t::hihat      },
  { "CHIP HAT O",  wav_chip_hat_open,   sizeof_wav_chip_hat_open,   sample_category_t::hihat      },
  { "CHIP TOM",    wav_chip_tom,        sizeof_wav_chip_tom,        sample_category_t::tom        },
  { "CHIP RIM",    wav_chip_rim,        sizeof_wav_chip_rim,        sample_category_t::percussion },
  { "CHIP COWBELL",wav_chip_cowbell,    sizeof_wav_chip_cowbell,    sample_category_t::percussion },
  { "DANCE KICK",   wav_dance_kick,       sizeof_wav_dance_kick,       sample_category_t::kick       },
  { "DANCE SNARE",  wav_dance_snare,      sizeof_wav_dance_snare,      sample_category_t::snare      },
  { "DANCE RIM",    wav_dance_rim,        sizeof_wav_dance_rim,        sample_category_t::percussion },
  { "DANCE CLAP",   wav_dance_clap,       sizeof_wav_dance_clap,       sample_category_t::percussion },
  { "DANCE TOM L",  wav_dance_tom_low,    sizeof_wav_dance_tom_low,    sample_category_t::tom        },
  { "DANCE TOM M",  wav_dance_tom_mid,    sizeof_wav_dance_tom_mid,    sample_category_t::tom        },
  { "DANCE TOM H",  wav_dance_tom_high,   sizeof_wav_dance_tom_high,   sample_category_t::tom        },
  { "DANCE HAT C",  wav_dance_hat_closed, sizeof_wav_dance_hat_closed, sample_category_t::hihat      },
  { "DANCE SHAKER", wav_dance_shaker,     sizeof_wav_dance_shaker,     sample_category_t::percussion },
  { "DANCE CRASH",  wav_dance_crash,      sizeof_wav_dance_crash,      sample_category_t::cymbal     },
  { "DANCE RIDE",   wav_dance_ride,       sizeof_wav_dance_ride,       sample_category_t::cymbal     },
  { "DANCE HAT O",  wav_dance_hat_open,   sizeof_wav_dance_hat_open,   sample_category_t::hihat      },
  { "DEEP KICK",    wav_preset_kick_deep,      sizeof_wav_preset_kick_deep,      sample_category_t::kick       },
  { "TIGHT KICK",   wav_preset_kick_tight,     sizeof_wav_preset_kick_tight,     sample_category_t::kick       },
  { "SOFT SNARE",   wav_preset_snare_soft,     sizeof_wav_preset_snare_soft,     sample_category_t::snare      },
  { "BRIGHT SNARE", wav_preset_snare_bright,   sizeof_wav_preset_snare_bright,   sample_category_t::snare      },
  { "SYNTH TOM LOW",wav_preset_tom_low,        sizeof_wav_preset_tom_low,        sample_category_t::tom        },
  { "SYNTH TOM HIGH",wav_preset_tom_high,      sizeof_wav_preset_tom_high,       sample_category_t::tom        },
  { "CLOSED HAT",   wav_preset_hihat_closed,   sizeof_wav_preset_hihat_closed,   sample_category_t::hihat      },
  { "OPEN HAT",     wav_preset_hihat_open,     sizeof_wav_preset_hihat_open,     sample_category_t::hihat      },
  { "SYNTH CRASH",  wav_preset_cymbal_crash,   sizeof_wav_preset_cymbal_crash,   sample_category_t::cymbal     },
  { "SYNTH RIDE",   wav_preset_cymbal_ride,    sizeof_wav_preset_cymbal_ride,    sample_category_t::cymbal     },
  { "SYNTH SHAKER", wav_preset_perc_shaker,    sizeof_wav_preset_perc_shaker,    sample_category_t::percussion },
  { "WOOD",         wav_preset_perc_wood,      sizeof_wav_preset_perc_wood,      sample_category_t::percussion },
  { "SUB BASS",     wav_preset_bass_sub,       sizeof_wav_preset_bass_sub,       sample_category_t::bass,     60,  60, 200,  8, 100 },
  { "SAW BASS",     wav_preset_bass_saw,       sizeof_wav_preset_bass_saw,       sample_category_t::bass,     60,  60, 200,  8, 100 },
  { "SQUARE LEAD",  wav_preset_lead_square,    sizeof_wav_preset_lead_square,    sample_category_t::lead,     60,  50, 200,  8, 120 },
  { "SYNC LEAD",    wav_preset_lead_sync,      sizeof_wav_preset_lead_sync,      sample_category_t::lead,     60,  50, 200,  8, 120 },
  { "WARM PAD",     wav_preset_pad_warm,       sizeof_wav_preset_pad_warm,       sample_category_t::pad,      60, 190, 340, 12, 480 },
  { "AIRY PAD",     wav_preset_pad_airy,       sizeof_wav_preset_pad_airy,       sample_category_t::pad,      60, 190, 340, 12, 480 },
  { "E PIANO",      wav_preset_keys_ep,        sizeof_wav_preset_keys_ep,        sample_category_t::keys,     60, 120, 260,  8, 220 },
  { "ORGAN",        wav_preset_keys_organ,     sizeof_wav_preset_keys_organ,     sample_category_t::keys,     60, 120, 260,  8, 220 },
  { "NYLON PLUCK",  wav_preset_pluck_nylon,    sizeof_wav_preset_pluck_nylon,    sample_category_t::pluck,    60, 140, 260,  8, 160 },
  { "HARP PLUCK",   wav_preset_pluck_harp,     sizeof_wav_preset_pluck_harp,     sample_category_t::pluck,    60, 140, 260,  8, 160 },
  { "BELL",         wav_preset_mallet_bell,    sizeof_wav_preset_mallet_bell,    sample_category_t::mallet,   60, 160, 280,  8, 280 },
  { "MARIMBA",      wav_preset_mallet_marimba, sizeof_wav_preset_mallet_marimba, sample_category_t::mallet,   60, 160, 280,  8, 280 },
  { "VOICE AH",     wav_preset_voice_ah,       sizeof_wav_preset_voice_ah,       sample_category_t::voice,    60, 130, 280, 10, 260 },
  { "VOICE OOH",    wav_preset_voice_ooh,      sizeof_wav_preset_voice_ooh,      sample_category_t::voice,    60, 130, 280, 10, 260 },
  { "RISER",        wav_preset_fx_riser,       sizeof_wav_preset_fx_riser,       sample_category_t::fx         },
  { "FALL",         wav_preset_fx_fall,        sizeof_wav_preset_fx_fall,        sample_category_t::fx         },
  { "SINE C4",      wav_preset_wave_sine,      sizeof_wav_preset_wave_sine,      sample_category_t::waveform, 60,  20, 140,  6,  80 },
  { "SAW C4",       wav_preset_wave_saw,       sizeof_wav_preset_wave_saw,       sample_category_t::waveform, 60,  20, 140,  6,  80 },
};
static constexpr const size_t builtin_sample_count = sizeof(builtin_samples) / sizeof(builtin_samples[0]);
// The factory kit intentionally leaves the top row empty. Additional built-in
// sounds remain available from Import Sample without changing this layout.
static constexpr const size_t builtin_default_sample_count = 8;

struct background_source_t {
  const char* file;
  sample_source_t source;
};

// Audio Beat files are distributed through File Editor/SD. Keeping the
// built-in list empty reserves flash for short playable instruments instead.
static constexpr std::array<background_source_t, 0> builtin_audio_beats = {};
static constexpr size_t builtin_audio_beat_count = builtin_audio_beats.size();

//-------------------------------------------------------------------------
} // namespace sampler_ns

#endif
