// SPDX-License-Identifier: MIT
// Copyright (c) 2026 InstaChord Corp.

#ifndef KANTAN_SAMPLER_SAMPLES_HPP
#define KANTAN_SAMPLER_SAMPLES_HPP

// 開発検証用の組み込みサンプル音源 (docs/Sample_Sound/ の WAV をバイナリ埋め込み)
// 将来的には TFカードからの読み込み・ユーザー録音に置き換える。
// アセンブラシンボルを定義するため、このヘッダは1つの翻訳単位からのみ include すること。
// (埋め込み手法は main/file_manage.cpp の IMPORT_FILE と同一)

#include <stdint.h>
#include <stddef.h>
#include <array>

namespace sampler_ns {
//-------------------------------------------------------------------------

#if defined (__APPLE__) && defined (__MACH__) && defined (__arm64__)

#define SAMPLER_IMPORT_WAV(filename, symbol) \
extern "C" const uint8_t symbol[], sizeof_##symbol[]; \
asm (\
  ".section __DATA,__data \n"\
  ".balign 4\n_"\
  #symbol ":\n"\
  ".incbin \"docs/Sample_Sound/" filename "\"\n"\
  ".global _sizeof_" #symbol "\n"\
  ".set _sizeof_" #symbol ", . - _" #symbol "\n"\
  ".global _" #symbol "\n"\
  ".balign 4\n"\
  ".text \n")

#else

#define SAMPLER_IMPORT_WAV(filename, symbol) \
extern "C" const uint8_t symbol[], sizeof_##symbol[]; \
asm (\
  ".section .rodata\n"\
  ".balign 4\n"\
  ".global " #symbol "\n"\
  #symbol ":\n"\
  ".incbin \"docs/Sample_Sound/" filename "\"\n"\
  ".global sizeof_" #symbol "\n"\
  ".set sizeof_" #symbol ", . - " #symbol "\n"\
  ".balign 4\n"\
  ".section \".text\"\n")

#endif

SAMPLER_IMPORT_WAV("kick.wav",                                wav_kick);
SAMPLER_IMPORT_WAV("Snare.wav",                               wav_snare);
SAMPLER_IMPORT_WAV("clap.wav",                                wav_clap);
#if defined(KANPLAY_AMY_INTEGRATION)
SAMPLER_IMPORT_WAV("Acoustic_Drums/08_Acoustic_Hat_Open.wav", wav_hihat);
#else
SAMPLER_IMPORT_WAV("Hat.wav",                                 wav_hihat);
#endif
SAMPLER_IMPORT_WAV("chin.wav",                                wav_chin);
#if defined(KANPLAY_AMY_INTEGRATION)
SAMPLER_IMPORT_WAV("Acoustic_Drums/09_Acoustic_Cowbell.wav",  wav_cowbell);
#else
SAMPLER_IMPORT_WAV("Cowbell.wav",                             wav_cowbell);
#endif
SAMPLER_IMPORT_WAV("Piko.wav",                                wav_piko);
SAMPLER_IMPORT_WAV("Tom.wav",                                 wav_tom);
SAMPLER_IMPORT_WAV("Air-Horn.wav",                            wav_air_horn);
SAMPLER_IMPORT_WAV("Cat.wav",                                 wav_cat);
SAMPLER_IMPORT_WAV("Gunshot.wav",                             wav_gunshot);
SAMPLER_IMPORT_WAV("Hat_Close.wav",                           wav_hat_close);
SAMPLER_IMPORT_WAV("Jump.wav",                                wav_jump);
SAMPLER_IMPORT_WAV("Laser.wav",                               wav_laser);
SAMPLER_IMPORT_WAV("Sheep.wav",                               wav_sheep);
SAMPLER_IMPORT_WAV("Acoustic_Drums/01_Acoustic_Tom_Low.wav",  wav_acoustic_tom_low);
SAMPLER_IMPORT_WAV("Acoustic_Drums/02_Acoustic_Tom_Mid.wav",  wav_acoustic_tom_mid);
SAMPLER_IMPORT_WAV("Acoustic_Drums/03_Acoustic_Tom_High.wav", wav_acoustic_tom_high);
SAMPLER_IMPORT_WAV("Acoustic_Drums/04_Acoustic_Rim.wav",      wav_acoustic_rim);
SAMPLER_IMPORT_WAV("Acoustic_Drums/05_Acoustic_Crash.wav",    wav_acoustic_crash);
SAMPLER_IMPORT_WAV("Acoustic_Drums/07_Acoustic_Shaker.wav",   wav_acoustic_shaker);
#if !defined(KANPLAY_AMY_INTEGRATION)
SAMPLER_IMPORT_WAV("Acoustic_Drums/06_Acoustic_Ride.wav",     wav_acoustic_ride);
SAMPLER_IMPORT_WAV("Chiptune_Drums/01_Chip_Kick.wav",         wav_chip_kick);
SAMPLER_IMPORT_WAV("Chiptune_Drums/02_Chip_Snare.wav",        wav_chip_snare);
SAMPLER_IMPORT_WAV("Chiptune_Drums/03_Chip_Clap.wav",         wav_chip_clap);
SAMPLER_IMPORT_WAV("Chiptune_Drums/04_Chip_Hat_Closed.wav",   wav_chip_hat_closed);
SAMPLER_IMPORT_WAV("Chiptune_Drums/05_Chip_Hat_Open.wav",     wav_chip_hat_open);
SAMPLER_IMPORT_WAV("Chiptune_Drums/06_Chip_Tom.wav",          wav_chip_tom);
SAMPLER_IMPORT_WAV("Chiptune_Drums/07_Chip_Rim.wav",          wav_chip_rim);
SAMPLER_IMPORT_WAV("Chiptune_Drums/08_Chip_Cowbell.wav",      wav_chip_cowbell);
SAMPLER_IMPORT_WAV("Dance_Drums/01_Dance_Kick.wav",           wav_dance_kick);
SAMPLER_IMPORT_WAV("Dance_Drums/02_Dance_Snare.wav",          wav_dance_snare);
SAMPLER_IMPORT_WAV("Dance_Drums/03_Dance_Rim.wav",            wav_dance_rim);
SAMPLER_IMPORT_WAV("Dance_Drums/04_Dance_Clap.wav",           wav_dance_clap);
SAMPLER_IMPORT_WAV("Dance_Drums/05_Dance_Tom_Low.wav",        wav_dance_tom_low);
SAMPLER_IMPORT_WAV("Dance_Drums/06_Dance_Tom_Mid.wav",        wav_dance_tom_mid);
SAMPLER_IMPORT_WAV("Dance_Drums/07_Dance_Tom_High.wav",       wav_dance_tom_high);
SAMPLER_IMPORT_WAV("Dance_Drums/08_Dance_Hat_Closed.wav",     wav_dance_hat_closed);
SAMPLER_IMPORT_WAV("Dance_Drums/09_Dance_Shaker.wav",         wav_dance_shaker);
SAMPLER_IMPORT_WAV("Dance_Drums/10_Dance_Crash.wav",          wav_dance_crash);
SAMPLER_IMPORT_WAV("Dance_Drums/11_Dance_Ride.wav",           wav_dance_ride);
SAMPLER_IMPORT_WAV("Dance_Drums/12_Dance_Hat_Open.wav",       wav_dance_hat_open);
#endif
// Deterministic mono factory one-shots generated by generate_presets.py.
SAMPLER_IMPORT_WAV("Generated_Presets/Kick_Deep.wav",         wav_preset_kick_deep);
SAMPLER_IMPORT_WAV("Generated_Presets/Kick_Tight.wav",        wav_preset_kick_tight);
SAMPLER_IMPORT_WAV("Generated_Presets/Snare_Soft.wav",        wav_preset_snare_soft);
SAMPLER_IMPORT_WAV("Generated_Presets/Snare_Bright.wav",      wav_preset_snare_bright);
SAMPLER_IMPORT_WAV("Generated_Presets/Tom_Low.wav",           wav_preset_tom_low);
SAMPLER_IMPORT_WAV("Generated_Presets/Tom_High.wav",          wav_preset_tom_high);
SAMPLER_IMPORT_WAV("Generated_Presets/HiHat_Closed.wav",      wav_preset_hihat_closed);
SAMPLER_IMPORT_WAV("Generated_Presets/HiHat_Open.wav",        wav_preset_hihat_open);
SAMPLER_IMPORT_WAV("Generated_Presets/Cymbal_Crash.wav",      wav_preset_cymbal_crash);
SAMPLER_IMPORT_WAV("Generated_Presets/Cymbal_Ride.wav",       wav_preset_cymbal_ride);
SAMPLER_IMPORT_WAV("Generated_Presets/Perc_Shaker.wav",       wav_preset_perc_shaker);
SAMPLER_IMPORT_WAV("Generated_Presets/Perc_Wood.wav",         wav_preset_perc_wood);
SAMPLER_IMPORT_WAV("Generated_Presets/FX_Riser.wav",          wav_preset_fx_riser);
SAMPLER_IMPORT_WAV("Generated_Presets/FX_Fall.wav",           wav_preset_fx_fall);
// Short voice one-shots. These are intentionally regular sample presets,
// rather than pitched KANTAN Synth tones.
SAMPLER_IMPORT_WAV("Voice/v_1.wav",                            wav_voice_1);
SAMPLER_IMPORT_WAV("Voice/v_2.wav",                            wav_voice_2);
SAMPLER_IMPORT_WAV("Voice/v_3.wav",                            wav_voice_3);
SAMPLER_IMPORT_WAV("Voice/v_4.wav",                            wav_voice_4);
SAMPLER_IMPORT_WAV("Voice/v_Go.wav",                           wav_voice_go);
SAMPLER_IMPORT_WAV("Voice/v_Ha.wav",                           wav_voice_ha);
SAMPLER_IMPORT_WAV("Voice/v_Hey.wav",                          wav_voice_hey);
SAMPLER_IMPORT_WAV("Voice/v_Yeah.wav",                         wav_voice_yeah);
SAMPLER_IMPORT_WAV("Voice/v_jp_Hai.wav",                       wav_voice_hai);

// Keep complete .ktsynth containers so built-in and SD tones share one parser.
SAMPLER_IMPORT_WAV("KANTAN_Synth/Alto_Sax_Alto_Sax-D4.ktsynth",                   ktsynth_alto_sax);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Celeste_Celeste-A4.ktsynth",                     ktsynth_celeste);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Distortion_Guitar_Distortion_Guitar-B3.ktsynth", ktsynth_dist_guitar);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Dulcimer_Dulcimer-C_4.ktsynth",                  ktsynth_dulcimer);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Marimba_Marimba-C4.ktsynth",                     ktsynth_marimba);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Percussive_Organ_Organ_Slow-D_3.ktsynth",         ktsynth_perc_organ);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Pick_Bass_Pick_Bass-D1.ktsynth",                 ktsynth_pick_bass);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Saw_Lead-F_4.ktsynth",                          ktsynth_saw_lead);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Polysynth_Synth_Strings_1-C42.ktsynth",           ktsynth_polysynth);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Slap_Bass_1_Slap_Bass_1-E3.ktsynth",             ktsynth_slap_bass);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Steel_Guitar_Steel_Guitar-B4.ktsynth",           ktsynth_steel_guitar);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Synth_Bass_2_Synth_Bass_2-B1.ktsynth",           ktsynth_synth_bass);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Synth_Strings_2_Synth_Strings_2-C3.ktsynth",      ktsynth_synth_strings);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Vibraphone_Vibraphone-D4.ktsynth",               ktsynth_vibraphone);
SAMPLER_IMPORT_WAV("KANTAN_Synth/Voice_Oohs_Voice_Oohs-B2.ktsynth",               ktsynth_voice_ooh);

#undef SAMPLER_IMPORT_WAV

enum class sample_category_t : uint8_t {
  kick,
  snare,
  tom,
  hihat,
  cymbal,
  percussion,
  bass,
  lead,
  pad,
  keys,
  pluck,
  mallet,
  voice,
  fx,
  waveform,
  count,
};

static constexpr const char* sample_category_names[] = {
  "Kick", "Snare", "Tom", "HiHat", "Cymbal", "Percussion",
  "Bass", "Lead", "Pad", "Keys", "Pluck", "Mallet", "Voice", "FX", "Waveform",
};
static constexpr size_t sample_category_count = (size_t)sample_category_t::count;
static_assert(sizeof(sample_category_names) / sizeof(sample_category_names[0]) == sample_category_count,
              "sample category name table mismatch");

// Categories with no remaining built-in entries are hidden. SD Card remains
// a separate final choice in the UI.
static constexpr sample_category_t sample_browser_categories[] = {
  sample_category_t::kick, sample_category_t::snare, sample_category_t::tom,
  sample_category_t::hihat, sample_category_t::cymbal,
  sample_category_t::percussion, sample_category_t::voice, sample_category_t::fx,
};
static constexpr size_t sample_browser_category_count =
  sizeof(sample_browser_categories) / sizeof(sample_browser_categories[0]);

static constexpr const char* sample_category_name(sample_category_t category)
{
  const size_t index = (size_t)category;
  return index < sample_category_count ? sample_category_names[index] : "Other";
}

struct sample_source_t {
  const char* name;        // Pad表示用の短い名前
  const uint8_t* data;     // WAVファイル先頭
  const uint8_t* size_sym; // サイズシンボル (アドレス値がサイズ)
  sample_category_t category = sample_category_t::fx;
  // -1: no authored Beat Anchor. Non-negative values place the perceived
  // vowel/onset on the Note Grid while retaining the consonant as pre-roll.
  int16_t beat_anchor_ms = -1;
  uint8_t base_note = 0xFF;  // 0xFF=自動解析。短尺シンセ素材はC4(60)を明示。
  uint16_t synth_loop_start_ms = 0;
  uint16_t synth_loop_end_ms = 0;
  uint16_t synth_loop_crossfade_ms = 0;
  uint16_t synth_release_ms = 120;
  uint16_t synth_attack_ms = 0;
  int16_t synth_tune_cents = 0;
  uint16_t default_gain_q8 = 256;
  size_t size(void) const { return (size_t)size_sym; }
  bool hasSynthPreset(void) const {
    return base_note <= 127 && synth_loop_end_ms > synth_loop_start_ms;
  }
};

static const sample_source_t builtin_samples[] = {
  { "KICK",    wav_kick,          sizeof_wav_kick,          sample_category_t::kick       },
  { "SNARE",   wav_snare,         sizeof_wav_snare,         sample_category_t::snare      },
  { "CLAP",    wav_clap,          sizeof_wav_clap,          sample_category_t::percussion },
  { "HAT",     wav_hihat,         sizeof_wav_hihat,         sample_category_t::hihat      },
  { "PIKO",    wav_piko,          sizeof_wav_piko,          sample_category_t::fx         },
  { "COWBELL", wav_cowbell,       sizeof_wav_cowbell,       sample_category_t::percussion },
  { "CHIN",    wav_chin,          sizeof_wav_chin,          sample_category_t::cymbal     },
  { "TOM",     wav_tom,           sizeof_wav_tom,           sample_category_t::tom        },
  { "AIR HORN", wav_air_horn,      sizeof_wav_air_horn,      sample_category_t::fx         },
  { "CAT",      wav_cat,           sizeof_wav_cat,           sample_category_t::voice      },
  { "GUNSHOT",  wav_gunshot,       sizeof_wav_gunshot,       sample_category_t::fx         },
  { "HAT CLOSE",wav_hat_close,     sizeof_wav_hat_close,     sample_category_t::hihat      },
  { "JUMP",     wav_jump,          sizeof_wav_jump,          sample_category_t::fx         },
  { "LASER",    wav_laser,         sizeof_wav_laser,         sample_category_t::fx         },
  { "SHEEP",    wav_sheep,         sizeof_wav_sheep,         sample_category_t::voice      },
  { "TOM LOW",  wav_acoustic_tom_low,  sizeof_wav_acoustic_tom_low,  sample_category_t::tom        },
  { "TOM MID",  wav_acoustic_tom_mid,  sizeof_wav_acoustic_tom_mid,  sample_category_t::tom        },
  { "TOM HIGH", wav_acoustic_tom_high, sizeof_wav_acoustic_tom_high, sample_category_t::tom        },
  { "RIM",      wav_acoustic_rim,      sizeof_wav_acoustic_rim,      sample_category_t::percussion },
  { "CRASH",    wav_acoustic_crash,    sizeof_wav_acoustic_crash,    sample_category_t::cymbal     },
  { "SHAKER",   wav_acoustic_shaker,   sizeof_wav_acoustic_shaker,   sample_category_t::percussion },
#if !defined(KANPLAY_AMY_INTEGRATION)
  { "RIDE",     wav_acoustic_ride,     sizeof_wav_acoustic_ride,     sample_category_t::cymbal     },
  { "CHIP KICK",   wav_chip_kick,       sizeof_wav_chip_kick,       sample_category_t::kick       },
  { "CHIP SNARE",  wav_chip_snare,      sizeof_wav_chip_snare,      sample_category_t::snare      },
  { "CHIP CLAP",   wav_chip_clap,       sizeof_wav_chip_clap,       sample_category_t::percussion },
  { "CHIP HAT C",  wav_chip_hat_closed, sizeof_wav_chip_hat_closed, sample_category_t::hihat      },
  { "CHIP HAT O",  wav_chip_hat_open,   sizeof_wav_chip_hat_open,   sample_category_t::hihat      },
  { "CHIP TOM",    wav_chip_tom,        sizeof_wav_chip_tom,        sample_category_t::tom        },
  { "CHIP RIM",    wav_chip_rim,        sizeof_wav_chip_rim,        sample_category_t::percussion },
  { "CHIP COWBELL",wav_chip_cowbell,    sizeof_wav_chip_cowbell,    sample_category_t::percussion },
  { "DANCE KICK",   wav_dance_kick,       sizeof_wav_dance_kick,       sample_category_t::kick       },
  { "DANCE SNARE",  wav_dance_snare,      sizeof_wav_dance_snare,      sample_category_t::snare      },
  { "DANCE RIM",    wav_dance_rim,        sizeof_wav_dance_rim,        sample_category_t::percussion },
  { "DANCE CLAP",   wav_dance_clap,       sizeof_wav_dance_clap,       sample_category_t::percussion },
  { "DANCE TOM L",  wav_dance_tom_low,    sizeof_wav_dance_tom_low,    sample_category_t::tom        },
  { "DANCE TOM M",  wav_dance_tom_mid,    sizeof_wav_dance_tom_mid,    sample_category_t::tom        },
  { "DANCE TOM H",  wav_dance_tom_high,   sizeof_wav_dance_tom_high,   sample_category_t::tom        },
  { "DANCE HAT C",  wav_dance_hat_closed, sizeof_wav_dance_hat_closed, sample_category_t::hihat      },
  { "DANCE SHAKER", wav_dance_shaker,     sizeof_wav_dance_shaker,     sample_category_t::percussion },
  { "DANCE CRASH",  wav_dance_crash,      sizeof_wav_dance_crash,      sample_category_t::cymbal     },
  { "DANCE RIDE",   wav_dance_ride,       sizeof_wav_dance_ride,       sample_category_t::cymbal     },
  { "DANCE HAT O",  wav_dance_hat_open,   sizeof_wav_dance_hat_open,   sample_category_t::hihat      },
#endif
  { "DEEP KICK",    wav_preset_kick_deep,      sizeof_wav_preset_kick_deep,      sample_category_t::kick       },
  { "TIGHT KICK",   wav_preset_kick_tight,     sizeof_wav_preset_kick_tight,     sample_category_t::kick       },
  { "SOFT SNARE",   wav_preset_snare_soft,     sizeof_wav_preset_snare_soft,     sample_category_t::snare      },
  { "BRIGHT SNARE", wav_preset_snare_bright,   sizeof_wav_preset_snare_bright,   sample_category_t::snare      },
  { "SYNTH TOM LOW",wav_preset_tom_low,        sizeof_wav_preset_tom_low,        sample_category_t::tom        },
  { "SYNTH TOM HIGH",wav_preset_tom_high,      sizeof_wav_preset_tom_high,       sample_category_t::tom        },
  { "CLOSED HAT",   wav_preset_hihat_closed,   sizeof_wav_preset_hihat_closed,   sample_category_t::hihat      },
  { "OPEN HAT",     wav_preset_hihat_open,     sizeof_wav_preset_hihat_open,     sample_category_t::hihat      },
  { "SYNTH CRASH",  wav_preset_cymbal_crash,   sizeof_wav_preset_cymbal_crash,   sample_category_t::cymbal     },
  { "SYNTH RIDE",   wav_preset_cymbal_ride,    sizeof_wav_preset_cymbal_ride,    sample_category_t::cymbal     },
  { "SYNTH SHAKER", wav_preset_perc_shaker,    sizeof_wav_preset_perc_shaker,    sample_category_t::percussion },
  { "WOOD",         wav_preset_perc_wood,      sizeof_wav_preset_perc_wood,      sample_category_t::percussion },
  { "RISER",        wav_preset_fx_riser,       sizeof_wav_preset_fx_riser,       sample_category_t::fx         },
  { "FALL",         wav_preset_fx_fall,        sizeof_wav_preset_fx_fall,        sample_category_t::fx         },
  // Authored from the first stable voiced/vowel region of each waveform.
  // VOICE 1 begins on its vowel; the others retain their leading consonant.
  { "VOICE 1",      wav_voice_1,               sizeof_wav_voice_1,               sample_category_t::voice,  0 },
  { "VOICE 2",      wav_voice_2,               sizeof_wav_voice_2,               sample_category_t::voice, 40 },
  { "VOICE 3",      wav_voice_3,               sizeof_wav_voice_3,               sample_category_t::voice, 70 },
  { "VOICE 4",      wav_voice_4,               sizeof_wav_voice_4,               sample_category_t::voice, 65 },
  { "GO",           wav_voice_go,              sizeof_wav_voice_go,              sample_category_t::voice, 25 },
  { "HA",           wav_voice_ha,              sizeof_wav_voice_ha,              sample_category_t::voice, 75 },
  { "HEY",          wav_voice_hey,             sizeof_wav_voice_hey,             sample_category_t::voice, 40 },
  { "YEAH",         wav_voice_yeah,            sizeof_wav_voice_yeah,            sample_category_t::voice, 20 },
  { "HAI",          wav_voice_hai,             sizeof_wav_voice_hai,             sample_category_t::voice, 55 },
};
static constexpr const size_t builtin_sample_count = sizeof(builtin_samples) / sizeof(builtin_samples[0]);
// The factory kit intentionally leaves the top row empty. Additional built-in
// sounds remain available from Import Sample without changing this layout.
static constexpr const size_t builtin_default_sample_count = 8;

struct ktsynth_source_t {
  const char* name;
  const uint8_t* data;
  const uint8_t* size_sym;
  const char* genre;
  size_t size(void) const { return (size_t)size_sym; }
};

static const ktsynth_source_t builtin_ktsynths[] = {
  // Synthesizers first for immediate access during sound selection
  { "Saw Lead",      ktsynth_saw_lead,      sizeof_ktsynth_saw_lead,      "SYNTH"   },
  { "Polysynth",     ktsynth_polysynth,     sizeof_ktsynth_polysynth,     "SYNTH"   },
  { "Synth Strings", ktsynth_synth_strings, sizeof_ktsynth_synth_strings, "SYNTH"   },
  { "Voice Ooh",     ktsynth_voice_ooh,     sizeof_ktsynth_voice_ooh,     "SYNTH"   },
  // Keys
  { "Celeste",       ktsynth_celeste,       sizeof_ktsynth_celeste,       "KEYS"    },
  { "Perc Organ",    ktsynth_perc_organ,    sizeof_ktsynth_perc_organ,    "KEYS"    },
  // Mallets / plucked percussion
  { "Vibraphone",    ktsynth_vibraphone,    sizeof_ktsynth_vibraphone,    "MALLET"  },
  { "Marimba",       ktsynth_marimba,       sizeof_ktsynth_marimba,       "MALLET"  },
  { "Dulcimer",      ktsynth_dulcimer,      sizeof_ktsynth_dulcimer,      "MALLET"  },
  // Guitars
  { "Steel Guitar",  ktsynth_steel_guitar,  sizeof_ktsynth_steel_guitar,  "GUITAR"  },
  { "Dist Guitar",   ktsynth_dist_guitar,   sizeof_ktsynth_dist_guitar,   "GUITAR"  },
  // Basses
  { "Pick Bass",     ktsynth_pick_bass,     sizeof_ktsynth_pick_bass,     "BASS"    },
  { "Slap Bass",     ktsynth_slap_bass,     sizeof_ktsynth_slap_bass,     "BASS"    },
  { "Synth Bass",    ktsynth_synth_bass,    sizeof_ktsynth_synth_bass,    "BASS"    },
  // Winds
  { "Alto Sax",      ktsynth_alto_sax,      sizeof_ktsynth_alto_sax,      "WIND"    },
};
static constexpr size_t builtin_ktsynth_count =
  sizeof(builtin_ktsynths) / sizeof(builtin_ktsynths[0]);

struct background_source_t {
  const char* file;
  sample_source_t source;
};

// Audio Beat files are distributed through File Editor/SD. Keeping the
// built-in list empty reserves flash for short playable instruments instead.
static constexpr std::array<background_source_t, 0> builtin_audio_beats = {};
static constexpr size_t builtin_audio_beat_count = builtin_audio_beats.size();

//-------------------------------------------------------------------------
} // namespace sampler_ns

#endif
