ENTRY( 0, "Simple_Guitar.json")
ENTRY( 1, "Simple_Guitarx2.json")
ENTRY( 2, "Simple_Piano.json")
ENTRY( 3, "Pop01_16beatSw.json")
ENTRY( 4, "Pop09_Standard.json")
ENTRY( 5, "Rock04_Standard.json")
ENTRY( 6, "Rock07_8Beat.json")
ENTRY( 7, "Dance03_Euro.json")
ENTRY( 8, "Samba_1.json")
ENTRY( 9, "Ska_1.json")
ENTRY(10, "Orchestra_1.json")
ENTRY(11, "Orchestra_2.json")
