ENTRY( 0, "ObLaDi-ObLaDa.json")
ENTRY( 1, "StandByMe.json")
ENTRY( 2, "LovinYou.json")
ENTRY( 3, "LetItBe.json")
ENTRY( 4, "Perfect.json")
ENTRY( 5, "VirtualInsanity.json")
ENTRY( 6, "APT.json")
ENTRY( 7, "jpop.青空.json")
ENTRY( 8, "jpop.アゲハ蝶.json")
ENTRY( 9, "jpop.イイね.json")
ENTRY(10, "jpop.YELL.json")
ENTRY(11, "jpop.怪獣.json")
ENTRY(12, "jpop.GuitarKidsRhapsody.json")
ENTRY(13, "jpop.GetWild.json")
ENTRY(14, "jpop.少年時代.json")
ENTRY(15, "jpop.Train-Train.json")
ENTRY(16, "jpop.とんぼ.json")
ENTRY(17, "jpop.なごり雪.json")
ENTRY(18, "jpop.夏祭り.json")
ENTRY(19, "jpop.白日.json")
ENTRY(20, "jpop.晩餐歌.json")
ENTRY(21, "jpop.USA.json")
ENTRY(22, "jpop.夜に駆ける.json")
ENTRY(23, "jpop.LovePhantom.json")
ENTRY(24, "jpop.LoveLoveLove.json")
ENTRY(25, "jpop.リンダリンダ.json")
ENTRY(26, "store.呼び込み君.json")
ENTRY(27, "game.Star_SuperMarioBros.json")
